name: pypi deployer
true: workflow_dispatch
jobs:
  Linux-build:
    env:
      TWINE_PASSWORD: '${{ secrets.TWINE_PASSWORD }}'
      TWINE_USERNAME: '${{ secrets.TWINE_USERNAME }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build and upload manylinux wheels
        uses: Niraj-Kamdar/manylinux-wheel-builder@master
  Matrix-build:
    env:
      TWINE_PASSWORD: '${{ secrets.TWINE_PASSWORD }}'
      TWINE_USERNAME: '${{ secrets.TWINE_USERNAME }}'
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - name: build wheel
        run: |
          pip install wheel
          python setup.py bdist_wheel
      - continue-on-error: true
        name: upload wheel
        run: |
          pip install twine
          twine upload dist/*
    strategy:
      matrix:
        os:
          - macos-latest
          - windows-latest
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
