name: Build and download wheel
on: workflow_dispatch
jobs:
  buildwheel:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
        python-version: [ 3.8, 3.9 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: build wheel
        run: |
          ls
          mkdir -p path/to/artifact
          pip install pybind11
          pip install wheel
          python setup.py build_ext
          python setup.py install
          python setup.py bdist_wheel
      - name: upload_artifact
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: path/to/artifact
    
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: path/to/artifact
        
#  upload_artifact:
#    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v3
#
#      - run: mkdir -p path/to/artifact
#
#      - run: echo hello > path/to/artifact/world.txt
#
#      - uses: actions/upload-artifact@v3
#        with:
#          name: my-artifact
#          path: path/to/artifact/ # or path/to/artifact

