name: Build and upload to PyPI
true:
  workflow_dispatch:
jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build sdist
        run: pipx run build --sdist
      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz
  build_wheels:
    name: 'Build wheels on ${{ matrix.os }}'
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: actions/checkout@v2
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - windows-2019
          - macos-10.15
  upload_pypi:
    name: Upload to PyPI
    needs:
      - build_wheels
      - build_sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist
      - uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          password: '${{ secrets.PYPI_API_TOKEN }}'
          user: __token__
          verbose: true
