name: Build wheels

on: [push, workflow_dispatch]

jobs:
  buildwheels_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
        boost-version: ["1.79.0"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install boost
        run: |
          sudo apt-get install g++
          cd ${{ github.workspace }}
          cd scripts
          sudo chmod 755 "install_boost_python_linux.sh"
          bash install_boost_python_linux.sh -v ${{ matrix.python-version }} -p python -b ${{ matrix.boost-version }}
      - name: Build wheel
        run: |
          pip install wheel
          cd ${{ github.workspace }}
          python setup.py build_ext -l boost_python -L "/usr/local/lib" -I "/usr/local/include"
          python setup.py bdist_wheel

  buildwheels_win:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.9"]
        boost-version: ["1.79.0"]
        compiler-version: ["14.2"]
        arch: ["x64"]
        include:
          - compiler-version: "14.2"
            toolset: "14.29"
          # - compiler-version: "14.3"
          #   toolset: "14.32"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Init MSVC env
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch }}
        toolset: ${{ matrix.toolset }}
    - name: Install boost
      run: |
        cd ${{ github.workspace }}
        cd scripts
        install_boost_python_windows.bat -b ${{ matrix.boost-version }} -a ${{ matrix.arch }} -c ${{ matrix.compiler-version }}
      shell: cmd
    - name: Build wheel
      run: |
        cd ${{ github.workspace }}
        pip install wheel
        set boost_version=${{ matrix.boost-version }}
        set boost_version=%boost_version:~0,4%
        python setup.py build_ext -L D:\Boost\lib -I D:\Boost\include\boost-%boost_version:.=_%
        python setup.py bdist_wheel
      shell: cmd
  